"""
Phase G1 — bootstrap-dept.sh must generate a per-dept CLAUDE.md that boots
the new agent in auto-driving mode, AND emit a systemd unit pre-rendered
with the per-dept env file path, working dir, Telegram state dir.

Also tests --dry-run mode for the smoke harness.

Spec source: Phase G deliverable G1 (msg 2720, 2026-05-21).
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


# Re-use the run_bootstrap fixture from conftest.py


def test_bootstrap_generates_per_dept_claude_md(bootstrapped_repo: Path) -> None:
    """The bootstrapped repo must contain CLAUDE.md telling the agent to
    auto-drive the SKILL `department-onboarding-guide`."""
    claude_md = bootstrapped_repo / "CLAUDE.md"
    assert claude_md.exists(), "CLAUDE.md must be generated by bootstrap"
    text = claude_md.read_text(encoding="utf-8")
    # Must reference the SKILL by name.
    assert "department-onboarding-guide" in text, \
        "CLAUDE.md must reference the SKILL by name"
    # Must instruct the agent it is autonomous (does not wait).
    assert "autonom" in text.lower(), \
        "CLAUDE.md must declare the agent is autonomous"
    # Must reference Telegram as the ONLY channel.
    assert "telegram" in text.lower(), "CLAUDE.md must mention Telegram"
    # Must mention the per-dept bot handle convention.
    assert "bubbleops" in text.lower(), \
        "CLAUDE.md must mention the @bubbleops<slug>_bot convention"
    # Must enumerate the 7 éclosure steps (FR labels accepted).
    step_aliases = {
        "mandate": ("mandate", "mandat"),
        "missions": ("missions",),
        "layers": ("layers", "layer"),
        "skills": ("skills", "compétences", "competences"),
        "gates": ("gates", "garde-fous", "gate_policies", "garde-fou"),
        "dry-run": ("dry-run", "dry_run", "répétition", "repetition"),
        "activation": ("activation",),
    }
    low = text.lower()
    for canonical, options in step_aliases.items():
        assert any(o in low for o in options), \
            f"CLAUDE.md missing step '{canonical}' (any of: {options})"
    # Must specify the agent's language (English as of scaffold v2).
    assert "english" in low, \
        "CLAUDE.md must specify the agent voice language (english)"


def test_bootstrap_claude_md_substitutes_slug_and_display(bootstrapped_repo: Path) -> None:
    """The CLAUDE.md must substitute the actual slug + display name."""
    text = (bootstrapped_repo / "CLAUDE.md").read_text(encoding="utf-8")
    assert "smoke-test" in text or "smoketest" in text or "SmokeTest" in text, \
        "CLAUDE.md must contain the slug"
    assert "SmokeTest" in text, "CLAUDE.md must contain the display name"


def test_bootstrap_generates_systemd_unit_in_repo(bootstrapped_repo: Path) -> None:
    """The bootstrapped repo must contain deploy/ops-loop-<slug>.service
    (rendered from deploy/templates/ops-loop-dept.service.template)."""
    unit_path = bootstrapped_repo / "deploy" / "ops-loop-smoke-test.service"
    assert unit_path.exists(), \
        f"systemd unit missing at {unit_path}"
    text = unit_path.read_text(encoding="utf-8")
    # Must NOT contain unsubstituted ${DEPT_SLUG} placeholders.
    assert "${DEPT_SLUG}" not in text, \
        "systemd unit must have DEPT_SLUG substituted"
    assert "smoke-test" in text, \
        "systemd unit must reference the dept slug"
    # Must use script(1) per doctrine Ban #1 (in ExecStart, not just comments).
    exec_lines = [ln for ln in text.splitlines()
                  if ln.startswith("ExecStart=") and not ln.startswith("ExecStartPre=")]
    assert exec_lines, "must have an ExecStart= line"
    exec_text = "\n".join(exec_lines)
    assert "/usr/bin/script" in exec_text, \
        "ExecStart must use /usr/bin/script (Ban #1)"
    # Must NOT use tmux in ExecStart per doctrine Ban #1.
    assert "tmux" not in exec_text, \
        f"ExecStart must NOT use tmux (Ban #1); got: {exec_text}"
    # Must NOT use `claude -p` or --print per doctrine Ban #2.
    assert "claude -p" not in exec_text, \
        "ExecStart must NOT use 'claude -p' (Ban #2)"
    assert "--print" not in exec_text, \
        "ExecStart must NOT use '--print' (Ban #2)"
    # Must use interactive claude with --dangerously-skip-permissions.
    assert "--dangerously-skip-permissions" in exec_text
    assert "--channels plugin:telegram@claude-plugins-official" in exec_text
    # Per-dept env file path
    assert "/run/claude-agent-smoke-test/env" in text
    # Per-dept Telegram state dir
    assert "/home/claude/.claude/channels/telegram-smoke-test" in text
    # Per-dept working dir
    assert "/home/claude/agents/smoke-test" in text


def test_bootstrap_emits_botfather_instruction(bootstrapped_repo: Path, run_bootstrap) -> None:
    """The bootstrap output must instruct the operator to create the per-dept
    Telegram bot via BotFather and paste the token."""
    # Find the stdout from the most recent bootstrap; we re-run quickly here.
    # Instead of re-running, check that NEXT STEPS mention BotFather/the bot.
    # The bootstrapped_repo fixture has already run once; we just inspect
    # the stdout of a separate invocation.
    # Simpler: run bootstrap with a different slug & inspect stdout.
    res = run_bootstrap(slug="bottest", display_name="BotTest", owner="operator")
    combined = res.stdout + res.stderr
    assert "botfather" in combined.lower() or "@bubbleops" in combined.lower(), \
        f"bootstrap stdout must mention BotFather or @bubbleops bot creation; got:\n{combined}"
    assert "bubbleopsbottest_bot" in combined.lower() or "bubbleops_bottest_bot" in combined.lower() \
        or "bubbleopsbottest" in combined.lower(), \
        f"bootstrap must mention the dedicated bot handle; got:\n{combined}"


def test_bootstrap_supports_dry_run_mode(scripts_dir: Path, tmp_clone_dir: Path) -> None:
    """--dry-run renders the skeleton to a local tmp dir without invoking gh
    or git push. Used by the Phase G end-to-end smoke."""
    script = scripts_dir / "bootstrap-dept.sh"
    target = tmp_clone_dir / "bubble-ops-drysmoke"
    env = os.environ.copy()
    env["BUBBLE_BOOTSTRAP_CLONE_DIR"] = str(tmp_clone_dir)
    res = subprocess.run(
        [
            "bash", str(script),
            "--slug=drysmoke",
            "--display-name=DrySmoke",
            "--owner=operator",
            "--dry-run",
        ],
        env=env, capture_output=True, text=True,
    )
    assert res.returncode == 0, \
        f"--dry-run must exit 0; stdout={res.stdout}\nstderr={res.stderr}"
    # Skeleton + CLAUDE.md + systemd unit all rendered.
    assert (target / "CLAUDE.md").exists(), \
        f"dry-run must render CLAUDE.md at {target}"
    assert (target / "deploy" / "ops-loop-drysmoke.service").exists(), \
        "dry-run must render the systemd unit"
    assert (target / "dept.yaml.draft").exists(), \
        "dry-run must render dept.yaml.draft"
    assert (target / "onboarding" / "STATE.yaml").exists(), \
        "dry-run must render STATE.yaml"
