"""CLAUDE.md must include the 5 discipline principles (4 Karpathy + 1 bubble-ops).

{{OPERATOR}} directive (msg 2734 + 2737, 2026-05-21): non-tech users will ask our
agents for changes and improvements. Without baked-in discipline, the agents
will scope-creep, refactor unprompted, and accept ambiguous requests as if
they were clear directives. Karpathy's 4 CLAUDE.md principles (from
multica-ai/andrej-karpathy-skills) keep code-helper LLMs on rails — we adapt
them for our dept-running agents and add a 5th specific to bubble-ops:
"Stay in your action class" (never act outside what your gate_policies
authorize, even if asked politely).

The 5 principles must appear in the per-dept CLAUDE.md generated by
scripts/bootstrap-dept.sh, with Bureau-de-Cadre voice (French, 2e personne
for {{OPERATOR}}, 1ère personne for the agent, no jargon).

Reference:
- https://github.com/multica-ai/andrej-karpathy-skills (the 4 source principles)
- scripts/lib/scaffold.py::render_claude_md (the template we extend)
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make scripts/lib/ importable for the test
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_SCRIPTS_LIB = _PROJECT_ROOT / "scripts" / "lib"
if str(_SCRIPTS_LIB) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_LIB))

from scaffold import render_claude_md  # noqa: E402


def test_claude_md_contains_principle_1_reflechir_avant_agir():
    """Principle 1 — Think Before Acting (Karpathy 'Think Before Coding')."""
    body = render_claude_md("test-slug", "TestDept")
    # The principle's heading
    assert "Réfléchir avant d'agir" in body or "Réfléchir avant d'agir." in body, (
        "Principle 1 'Réfléchir avant d'agir' missing from CLAUDE.md"
    )
    # The principle's behavior: propose interpretations + ask rather than guess
    assert "interprétation" in body.lower() or "options" in body.lower(), (
        "Principle 1 must mention proposing multiple interpretations / options"
    )
    assert "deviner" in body.lower() or "ambigu" in body.lower(), (
        "Principle 1 must mention not guessing on ambiguity"
    )


def test_claude_md_contains_principle_2_simplicite_dabord():
    """Principle 2 — Simplicity First (Karpathy 'Simplicity First')."""
    body = render_claude_md("test-slug", "TestDept")
    assert "Simplicité d'abord" in body, (
        "Principle 2 'Simplicité d'abord' missing from CLAUDE.md"
    )
    assert ("minimum" in body.lower() or "minimal" in body.lower() or
            "viable" in body.lower()), (
        "Principle 2 must mention minimum viable / no speculative features"
    )


def test_claude_md_contains_principle_3_changements_chirurgicaux():
    """Principle 3 — Surgical Changes (Karpathy 'Surgical Changes')."""
    body = render_claude_md("test-slug", "TestDept")
    assert "Changements chirurgicaux" in body, (
        "Principle 3 'Changements chirurgicaux' missing from CLAUDE.md"
    )
    # The behavior: don't refactor adjacent unbroken code
    assert ("ne refactore pas" in body.lower() or "ne touche que" in body.lower() or
            "ne pas refactor" in body.lower() or "code adjacent" in body.lower()), (
        "Principle 3 must forbid refactoring adjacent unbroken code"
    )


def test_claude_md_contains_principle_4_critere_de_succes_verifiable():
    """Principle 4 — Goal-Driven Execution (Karpathy 'Goal-Driven Execution')."""
    body = render_claude_md("test-slug", "TestDept")
    assert ("Critère de succès vérifiable" in body or
            "Critères de succès vérifiables" in body or
            "But-orienté" in body), (
        "Principle 4 'Critère de succès vérifiable' missing from CLAUDE.md"
    )
    assert "vérifiable" in body.lower() or "vérifier" in body.lower(), (
        "Principle 4 must mention verifiable success criteria"
    )


def test_claude_md_contains_principle_5_reste_dans_ton_perimetre():
    """Principle 5 — Stay in your action class (bubble-ops specific)."""
    body = render_claude_md("test-slug", "TestDept")
    assert ("Reste dans ton périmètre" in body or
            "Reste dans ton scope" in body or
            "Reste dans ta classe d'action" in body), (
        "Principle 5 'Reste dans ton périmètre' missing from CLAUDE.md"
    )
    # The behavior: refuse out-of-scope requests; propose escalation
    assert ("gate_policies" in body or "gate policy" in body.lower() or
            "périmètre" in body.lower() or "scope" in body.lower()), (
        "Principle 5 must reference gate_policies / scope as the boundary"
    )
    assert ("escalad" in body.lower() or "joris" in body.lower() or
            "redirige" in body.lower()), (
        "Principle 5 must mention escalating / redirecting out-of-scope requests"
    )


def test_claude_md_principles_introduced_as_a_block():
    """The 5 principles must appear under a single discipline heading."""
    body = render_claude_md("test-slug", "TestDept")
    # A section heading that introduces the 5 principles
    assert ("Discipline" in body or "Garde-fous" in body or
            "Principes" in body), (
        "The 5 principles must live under a clear section heading "
        "(Discipline / Garde-fous / Principes)"
    )


def test_claude_md_bureau_de_cadre_voice_preserved():
    """The new principles must keep the Bureau-de-Cadre voice ({{OPERATOR}} in 2e
    personne, agent in 1ère personne, French, no English enum slugs)."""
    body = render_claude_md("test-slug", "TestDept")
    # Should NOT contain raw English principle names verbatim (those are
    # Karpathy's English headings; we translated them)
    forbidden_english = [
        "Think Before Coding",
        "Simplicity First",
        "Surgical Changes",
        "Goal-Driven Execution",
    ]
    for english in forbidden_english:
        assert english not in body, (
            f"CLAUDE.md contains English Karpathy heading {english!r} — "
            f"must be translated to French (Bureau-de-Cadre voice)"
        )


def test_claude_md_cites_karpathy_inspiration_in_a_comment():
    """The discipline section should briefly attribute the inspiration so a
    future maintainer can trace the design choice."""
    body = render_claude_md("test-slug", "TestDept")
    # A single mention of Karpathy / the source repo in a discreet comment
    assert ("Karpathy" in body or
            "multica-ai" in body or
            "andrej-karpathy-skills" in body), (
        "CLAUDE.md should attribute the 4 imported principles to Karpathy "
        "(one-line discreet mention so the design choice is traceable)"
    )
